### PR TITLE
Bone Arrows

### PR DESCRIPTION
**Pull request by Demetreo**
## About The Pull Request

Making Bone Arrow crafting and damage less broken. 

## Why It's Good For The Game

Because fixed arrows are fun

## Changelog
:cl:

tweak: No more need of Ashen Arrows for crafting Bone Arrows. Now they need 1 bone and 2 sinews.
balance: Wooden and Ashen Arrows now do more damage.
/:cl:

### CODE REVIEW

**Comment by SandPoot** [comment]
Very buff

**Comment by SandPoot** [comment]
arrow = 35 
ash = 45 
bone = 30 + armor penetration -10
put more info on your stuff

**Comment by TriggeredBoi** [comment]
> SandPoot requested review from SandPoot

**Comment by SandPoot** [comment]
> > SandPoot requested review from SandPoot
> 
> 

As if anyone, literally anyone else, is checking these.

**Pull request merged**
