### PR TITLE
Pref menu unbreak

### PR DESCRIPTION
**Pull request by SandPoot**
## About The Pull Request
Fixes pref menu

## Why It's Good For The Game
Fixes this

image
into
image

### CODE REVIEW

**Comment by TriggeredBoi** [comment]
image
Simple fix eh?

**Comment by SandPoot** [comment]
I... how the fuck did it get all of that, please look at the other one first then.

**Comment by TriggeredBoi** [comment]
You branched off your upstream branch, not master.

**Comment by SandPoot** [comment]
Beautiful, either way, look at the other one, this one won't move anywhere until the problem has been solved.

**Comment by SandPoot** [comment]
This all broke, yep, going for a new pr.

**Comment by SandPoot** [comment]
i love github btw

**Pull request closed without merging**
