### PR TITLE
EMERGENCY EMERGENCY FUC FUC FUC

### PR DESCRIPTION
**Pull request by TriggeredBoi**
oh no

### CODE REVIEW

**Comment by TriggeredBoi** [comment]
I....... I don't know. I'm completely clueless.

Who would win:
New era Headcoder
or
Some defines with a high number

**Comment by SandPoot** [comment]
Blame tg/goon

**Comment by yurksemesh** [comment]
> I....... I don't know. I'm completely clueless.
> 
> Who would win:
> New era Headcoder
> or
> Some defines with a high number

wait you're a head coder now

**Comment by TriggeredBoi** [comment]
I've... Kinda always been? Ever since Sand's brief ragequit from the community I just took his place as headcoder

**Comment by yurksemesh** [comment]
> I've... Kinda always been? Ever since Sand's brief ragequit from the community I just took his place as headcoder

Keep up the great work then.

**Comment by TriggeredBoi** [comment]
> Blame tg/goon

Just tried to replicate this cursed shit in TG, nothing happened. Means we can blame either Citadel or Skyrat, ahh the (few) advantages of being the upstream of an upstream of an upstream of an upstream.

**Comment by SandPoot** [comment]
The upstream-ception

**Pull request merged**
